# Generated by Django 5.2.17 on 2026-08-05 16:35

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_hostel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='year',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gmail_history_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gmail_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gmail_refresh_token',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, default='')),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hostel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(default=230002035, max_length=20),
            preserve_default=False,
        ),
    ]
