# Generated by Django 5.2.17 on 2026-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='embedding_processed_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='embedding_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('error', 'Error')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='embedding_total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
