# Generated by Django 5.2.17 on 2026-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentprofile_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gmail_watch_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
